### Create a review
POST http://localhost:3000/api/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmVhMDIxOWViYmZjMGFkYzZiMmZiZWIiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE2MDkxODQzOTgsImF1ZCI6InBvc3RtYW4iLCJpc3MiOiJzdHVkZW50Iiwic3ViIjoiVG9rZW4gcGVudHJ1IGxhYm9yYXRvcnVsIDYifQ.7HPHuhOikAep-5ovu6MeZxyRJQsGhrEHPElzMhnzLmc

{
   "text": "This sucks",
   "programId": "5fea2c072040a3c4757edeb6",
   "score": 7
}

### Get reviews
GET http://localhost:3000/api/review?page=0&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmVhMDIxOWViYmZjMGFkYzZiMmZiZWIiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE2MDkxODQzOTgsImF1ZCI6InBvc3RtYW4iLCJpc3MiOiJzdHVkZW50Iiwic3ViIjoiVG9rZW4gcGVudHJ1IGxhYm9yYXRvcnVsIDYifQ.7HPHuhOikAep-5ovu6MeZxyRJQsGhrEHPElzMhnzLmc
